---
title: "analisis"
output: html_document
---

```{r setup, include=FALSE}
library(fable)
library(feasts)
library(tsibble)
library(tsibbledata)
library(readxl)
library(tidyverse)
library(lubridate)
library(patchwork)
library(plotly)
library(gganimate)
library(quantmod)
#library(dplyr)
library(GGally)
library("easypackages")
packages("tidyverse","lubridate", "patchwork", "fpp2","fpp3","scales","DT")
```


```{r}
INPC <- read_excel("BD_INDICADORES_MACROECONOMICOS.xlsx", sheet = "INPC")
INPCJ <- INPC[INPC$`Nombre entidad` == "Jalisco",] 
INPCJ <- select(INPCJ, -"Clave entidad", -"Nombre entidad")
```

```{r}
ggplot(INPCJ, aes(x=Índice, group=`Objeto de gasto`, color=`Objeto de gasto`)) + 
  geom_boxplot(aes(fill=Índice))
```


```{r}
EXP<- read_excel("BD_INDICADORES_MACROECONOMICOS.xlsx", sheet = "Exportaciones")
EXPJ <- INPC[EXP$`Nombre entidad` == "Jalisco",] 
EXPJ <- select(EXPJ, -"Nombre entidad")
```



```{r, warning=FALSE}
ggplot(EXPJ, aes(x=log(`Exportaciones totales`), group=Subsector, color=Subsector)) + 
  geom_boxplot()
```

```{r, include=FALSE, warning=FALSE}
EXPJ <- EXPJ %>%
  mutate(Quarter =yearquarter(dmy(Fecha))) %>%
  select(-Fecha) %>%
  as_tsibble(key = c(Subsector), index = Quarter)
```


```{r}
EXPJ %>% 
  features(`Exportaciones totales`, c(list(mean =mean), list(min=min), list(max=max), list(sd=sd))) %>% datatable()
```










