---
title: "R Notebook"
output: html_notebook
---
```{r, include=FALSE}
library(fable)
library(feasts)
library(tsibble)
library(tsibbledata)
library(readxl)
library(tidyverse)
library(lubridate)
library(patchwork)
library(plotly)
library(gganimate)
library(quantmod)
#library(dplyr)
library(GGally)

```


```{r}
INPC <- read_excel("BD_INDICADORES_MACROECONOMICOS.xlsx", sheet = "INPC")
INPCJ <- INPC[INPC$`Nombre entidad` == "Jalisco",] 
INPCJ <- select(INPCJ, -"Clave entidad", -"Nombre entidad")
INPCJ_general <- INPCJ %>%
  filter(`Objeto de gasto` == "Índice General")
```


```{r}
INPCJ_general <- INPCJ_general %>%
  mutate(Month = yearmonth(Fecha)) %>%
  select(-Fecha) %>%
  as_tsibble(key = c(`Objeto de gasto`),
             index = Month)
```



```{r}
autoplot(INPCJ_general) 
```




```{r}
INPCJ_general %>%
  gg_season(Índice, labels = "both") +
  labs(y = "Indice",
       title = "Seasonal plot: INPC General")
```

```{r}
INPCJ_general %>%
  gg_subseries(Índice) +
  labs(y = "Indice",
    title = "Indice general INPC Jalisco" )
```

```{r}
INPCJ_G <- INPCJ %>%
  group_by(`Objeto de gasto`) 
INPCJ_G %>%
  ggplot(aes(x = Fecha, y = Índice)) +
  geom_line() +
  facet_grid(vars(`Objeto de gasto`), scales = "free_y")
```

```{r, warning=FALSE, message=FALSE}
INPCJ_G %>%
  pivot_wider(values_from=Índice, names_from=`Objeto de gasto`) %>%
  GGally::ggpairs(columns = 2:9)
```


```{r}
INPCJ_general %>% gg_lag(Índice, geom = "point", lag=3)
```


```{r}
INPCJ_general %>%
  ACF(Índice) %>%
  autoplot() + labs(title="INPC JALISCO INDICE GENERAL")
```


```{r}
INPC_av <- INPCJ_general %>%
  mutate(
    `5-MA` = slider::slide_dbl(Índice, mean,
                .before = 2, .after = 2, .complete = TRUE)
  )
```

```{r}
autoplot(INPC_av, Índice) +
  autolayer(INPC_av, `5-MA`, color = "red") +
  labs(x = "Periodo",
       title = "Índice general con medias ajustadas") +
  guides(colour = guide_legend(title = "series"))
```

```{r}
INPCJ_general %>%
  model(classical_decomposition(Índice, type = "additive")) %>%
  components() %>%
  autoplot() +
  labs(title = "Descomposicion INPC indice general")
```



```{r}
INPCJ_general_mut <- INPCJ_general %>%
  mutate(Índice = Índice / 100)
autoplot(INPCJ_general_mut)

```


```{r}
#duplicates(INPCJ)
#INPCJ<-tsibble(INPCJ)
INPCJ_general_mut<-tsibble(INPCJ_general_mut)

```


```{r}
fit <- INPCJ_general_mut %>%
  model(trend_model = TSLM(Índice ~ trend()))
```

```{r}
fit %>%
  forecast(h = "2 years") %>%
  autoplot(INPCJ_general_mut) +
  labs(y = "INDICE/100", title = "INPC INDICE GENERAL JALISCO")
```


```{r}
augment(fit) %>%
  ggplot(aes(x = Month)) +
  geom_line(aes(y = Índice, colour = "Data")) +
  geom_line(aes(y = .fitted, colour = "Fitted")) +
  labs(y = NULL,
    title = "INDICE GENERAL JALISCO"
  ) +
  scale_color_manual(values=c(Data="black",Fitted="red")) +
  guides(colour = guide_legend(title = NULL))
```




```{r}
residuos<-tsibble(augment(fit))
residuos
```



```{r}
residuos%>%
  model(NAIVE(Índice)) %>%
  gg_tsresiduals()
```

```{r}
residuos %>% features(.innov, box_pierce, lag = 2, dof = 0)
residuos %>% features(.innov, ljung_box, lag = 2, dof = 0)
```



FORECAST CON DESCOMPOSICION 

```{r}
fit_descompo <- INPCJ_general_mut %>%
  model(stlf = decomposition_model(
    STL(Índice ~ trend(window = 7), robust = TRUE),
    NAIVE(season_adjust)
  ))
fit_descompo %>%
  forecast() %>%
  autoplot(INPCJ_general_mut)+
  labs(y = "Indice",
       title = "INPC JALISCO INDICE GENERAL")
```

CROSS VALIDATION 

```{r}
INPCJ_general_mut_tr <- INPCJ_general_mut %>%
  stretch_tsibble(.init = 3, .step = 1)

INPCJ_general_mut_tr %>%
  model(RW(Índice ~ drift())) %>%
  forecast(h = 1) %>%
  accuracy(INPCJ_general_mut)
# Training set accuracy
INPCJ_general_mut %>%
  model(RW(Índice ~ drift())) %>%
  accuracy()
```















