---
title: "FORECAST INPC"
output: html_document
---

```{r, include=FALSE, warning=FALSE}
library(fable)
library(feasts)
library(tsibble)
library(tsibbledata)
library(readxl)
library(tidyverse)
library(lubridate)
library(patchwork)
library(plotly)
library(gganimate)
library(quantmod)
#library(dplyr)
library(GGally)
```


```{r, include=FALSE, warning=FALSE}
INPC <- read_excel("BD_INDICADORES_MACROECONOMICOS.xlsx", sheet = "INPC")
INPCJ <- INPC[INPC$`Nombre entidad` == "Jalisco",] 
INPCJ <- select(INPCJ, -"Clave entidad", -"Nombre entidad")
```


```{r, include=FALSE, warning=FALSE}
INPCJ <- INPCJ %>%
  mutate(Month = yearmonth(Fecha)) %>%
  select(-Fecha) %>%
  as_tsibble(key = c(`Objeto de gasto`),
             index = Month)
```


```{r, echo=FALSE, warning=FALSE, message=FALSE}
autoplot(INPCJ) 
```


```{r, fig.align='center', echo=FALSE}
INPCJ %>%
  filter(`Objeto de gasto` == "Índice General") %>%
  gg_season(Índice, labels = "both") +
  labs(y = "Indice",x="Mes",
       title = "Grafica estacional INPC General")+
  theme(plot.title = element_text(hjust = 0.5))

INPCJ %>% 
  filter(`Objeto de gasto` == "Índice General") %>%
  gg_subseries(Índice) +
  labs(y = "Indice", x="Mes",
    title = "Subserie de Índice General" )+
  theme(plot.title = element_text(hjust = 0.5))

INPCJ %>% 
  filter(`Objeto de gasto` == "Índice General") %>% 
  gg_lag(Índice, geom = "point", lags=1:3) +
  labs(title = "Diferenciacion en Índice General")+
  theme(plot.title = element_text(hjust = 0.5))

INPCJ %>%
  filter(`Objeto de gasto` == "Índice General") %>% 
  model(ARIMA(Índice)) %>% 
  forecast(h = "2 years") %>%
  autoplot(INPCJ) +
  labs(y = "Indice", title = "Pronóstico ARIMA (0,1,0) de Indice General")+
  theme(plot.title = element_text(hjust = 0.5))

```

```{r, fig.align='center', echo=FALSE}
INPCJ %>%
  filter(`Objeto de gasto` == "Alimentos, bebidas y tabaco")%>%
  gg_season(Índice, labels = "both") +
  labs(y = "Indice",x="Mes",
       title = "Grafica estacional de Alimentos, Bebidas y Tabaco")+
  theme(plot.title = element_text(hjust = 0.5))

INPCJ %>% 
  filter(`Objeto de gasto` == "Alimentos, bebidas y tabaco")%>%
  gg_subseries(Índice) +
  labs(y = "Indice", x="Mes",
    title = "Subserie de Alimentos, bebidas y tabaco" )+
  theme(plot.title = element_text(hjust = 0.5))

INPCJ %>% 
  filter(`Objeto de gasto` == "Alimentos, bebidas y tabaco")%>% 
  gg_lag(Índice, geom = "point", lags=1:3) +
  labs(title = "Diferenciacion en Alimentos, bebidas y tabaco")+
  theme(plot.title = element_text(hjust = 0.5))
  

INPCJ%>%
  filter(`Objeto de gasto` == "Alimentos, bebidas y tabaco") %>% 
  model(ARIMA(Índice)) %>% 
  forecast(h = "2 years") %>%
  autoplot(INPCJ) +
  labs(y = "Indice", title = "Pronóstico ARIMA (0,1,0) de Alimentos, bebidas y tabaco")+
  theme(plot.title = element_text(hjust = 0.5))

```


```{r, fig.align='center', echo=FALSE}
INPCJ %>%
  filter(`Objeto de gasto` == "Educación y esparcimiento")%>%
  gg_season(Índice, labels = "both") +
  labs(y = "Indice",x="Mes",
       title = "Grafica estacional de Educación y Esparcimiento")+
  theme(plot.title = element_text(hjust = 0.5))

INPCJ %>% 
  filter(`Objeto de gasto` == "Educación y esparcimiento")%>%
  gg_subseries(Índice) +
  labs(y = "Indice", x="Mes",
    title = "Subserie de Educación y Esparcimiento" )+
  theme(plot.title = element_text(hjust = 0.5))

INPCJ %>% 
  filter(`Objeto de gasto` == "Educación y esparcimiento")%>% 
  gg_lag(Índice, geom = "point", lags=1:3) +
  labs(title = "Diferenciacion en Educación y esparcimiento")+
  theme(plot.title = element_text(hjust = 0.5))

INPCJ%>%
  filter(`Objeto de gasto` == "Educación y esparcimiento") %>% 
  model(ARIMA(Índice)) %>% 
  forecast(h = "2 years") %>%
  autoplot(INPCJ) +
  labs(y = "Indice", title = "Pronóstico ARIMA (0,1,0) de Educación y esparcimiento")+
  theme(plot.title = element_text(hjust = 0.5))

```


```{r, fig.align='center', echo=FALSE}
INPCJ %>%
  filter(`Objeto de gasto` == "Muebles, aparatos y accesorios domésticos")%>%
  gg_season(Índice, labels = "both") +
  labs(y = "Indice",x="Mes",
       title = "Grafica estacional de Muebles, Aparatos y Accesorios Domésticos")+
  theme(plot.title = element_text(hjust = 0.5))

INPCJ %>% 
  filter(`Objeto de gasto` == "Muebles, aparatos y accesorios domésticos")%>%
  gg_subseries(Índice) +
  labs(y = "Indice", x="Mes",
    title = "Subserie de Muebles, Aparatos y Accesorios Domésticos" )+
  theme(plot.title = element_text(hjust = 0.5))

INPCJ %>% 
  filter(`Objeto de gasto` == "Muebles, aparatos y accesorios domésticos")%>% 
  gg_lag(Índice, geom = "point", lags=1:3) +
  labs(title = "Diferenciacion en Muebles, aparatos y accesorios domésticos")+
  theme(plot.title = element_text(hjust = 0.5))

INPCJ%>%
  filter(`Objeto de gasto` == "Muebles, aparatos y accesorios domésticos") %>% 
  model(ARIMA(Índice)) %>% 
  forecast(h = "2 years") %>%
  autoplot(INPCJ) +
  labs(y = "Indice", title = "Pronóstico ARIMA (0,1,0) de Muebles, aparatos y accesorios domésticos")+
  theme(plot.title = element_text(hjust = 0.5))
```


```{r, fig.align='center', echo=FALSE}
INPCJ %>%
  filter(`Objeto de gasto` == "Otros servicios")%>%
  gg_season(Índice, labels = "both") +
  labs(y = "Indice",x="Mes",
       title = "Grafica estacional de Otros Servicios")+
  theme(plot.title = element_text(hjust = 0.5))

INPCJ %>% 
  filter(`Objeto de gasto` == "Otros servicios")%>%
  gg_subseries(Índice) +
  labs(y = "Indice", x="Mes",
    title = "Subserie de Otros servicios" )+
  theme(plot.title = element_text(hjust = 0.5))

INPCJ %>% 
  filter(`Objeto de gasto` == "Otros servicios")%>% 
  gg_lag(Índice, geom = "point", lags=1:3) +
  labs(title = "Diferenciacion en Otros servicios")+
  theme(plot.title = element_text(hjust = 0.5))

INPCJ%>%
  filter(`Objeto de gasto` == "Otros servicios") %>% 
  model(ARIMA(Índice)) %>% 
  forecast(h = "2 years") %>%
  autoplot(INPCJ) +
  labs(y = "Indice", title = "Pronóstico ARIMA (0,1,0) de Otros servicios")+
  theme(plot.title = element_text(hjust = 0.5))
```


```{r, fig.align='center', echo=FALSE}
INPCJ %>%
  filter(`Objeto de gasto` == "Ropa, calzado y accesorios")%>%
  gg_season(Índice, labels = "both") +
  labs(y = "Indice",x="Mes",
       title = "Grafica estacional de Ropa, Calzado y Accesorios")+
  theme(plot.title = element_text(hjust = 0.5))

INPCJ %>% 
  filter(`Objeto de gasto` == "Ropa, calzado y accesorios")%>%
  gg_subseries(Índice) +
  labs(y = "Indice", x="Mes",
    title = "Subserie de Ropa, calzado y Accesorios" )+
  theme(plot.title = element_text(hjust = 0.5))

INPCJ %>% 
  filter(`Objeto de gasto` == "Ropa, calzado y accesorios")%>% 
  gg_lag(Índice, geom = "point", lags=1:3) +
  labs(title = "Diferenciacion en Ropa, calzado y accesorios")+
  theme(plot.title = element_text(hjust = 0.5))

INPCJ%>%
  filter(`Objeto de gasto` == "Ropa, calzado y accesorios") %>% 
  model(ARIMA(Índice)) %>% 
  forecast(h = "2 years") %>%
  autoplot(INPCJ) +
  labs(y = "Indice", title = "Pronóstico ARIMA (0,1,0) de Ropa, calzado y accesorios")+
  theme(plot.title = element_text(hjust = 0.5))

```


```{r, fig.align='center', echo=FALSE}
INPCJ %>%
  filter(`Objeto de gasto` == "Salud y cuidado personal")%>%
  gg_season(Índice, labels = "both") +
  labs(y = "Indice",x="Mes",
       title = "Grafica estacional de Salud y Cuidado Personal")+
  theme(plot.title = element_text(hjust = 0.5))

INPCJ %>% 
  filter(`Objeto de gasto` == "Salud y cuidado personal")%>%
  gg_subseries(Índice) +
  labs(y = "Indice", x="Mes",
    title = "Subserie de Salud y cuidado personal" )+
  theme(plot.title = element_text(hjust = 0.5))

INPCJ %>% 
  filter(`Objeto de gasto` == "Salud y cuidado personal")%>% 
  gg_lag(Índice, geom = "point", lags=1:3) +
  labs(title = "Diferenciacion en Salud y cuidado personal")+
  theme(plot.title = element_text(hjust = 0.5))

INPCJ%>%
  filter(`Objeto de gasto` == "Salud y cuidado personal") %>% 
  model(ARIMA(Índice)) %>% 
  forecast(h = "2 years") %>%
  autoplot(INPCJ) +
  labs(y = "Indice", title = "Pronóstico ARIMA (0,1,0) de Salud y cuidado personal")+
  theme(plot.title = element_text(hjust = 0.5))
```



```{r, warning=FALSE, message=FALSE, echo=TRUE,fig.align='center'}
INPCJ %>%
  pivot_wider(values_from=Índice, names_from=`Objeto de gasto`) %>%
  GGally::ggpairs(columns = 2:9)
```



```{r}
INPCJ %>%
  filter(`Objeto de gasto` == "Índice General")

```









